GET http://localhost:3000/posts
Authorization: Bearer 

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": ""
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
	"refreshToken": ""
}

DELETE http://localhost:3000/logout
Content-Type: application/json

{
	"refreshToken": ""
}